Add CI
Signed-off-by: v.oleynikov <vasily.oleynikov@flant.com>

diff --git a/.github/workflows/go_tests.yaml b/.github/workflows/go_tests.yaml
--- a/.github/workflows/go_tests.yaml
+++ b/.github/workflows/go_tests.yaml
@@ -4,32 +4,48 @@ description: "Go tests"
 env:
   GO_BUILD_TAGS: "ce ee se seplus csepro"
 
-runs:
-  using: "composite"
-  steps:
-    - name: Setup Go environment
-      uses: actions/setup-go@v5
-      with:
-        go-version: "1.24"
+on:
+  #pull_request:
+  # call from trivy_image_check.yaml, which in turn call from pull_request
+  # https://stackoverflow.com/a/71489231
+  workflow_call:
+  push:
+    branches:
+      - main
 
-    - name: Run Go tests
-      shell: bash
-      run: |
-        basedir=$(pwd)
-        failed='false'
-        for i in $(find / -type f -name '*_test.go');do
-          dir=$(echo $i | sed 's/[a-z_A-Z0-9-]*_test.go$//')
-          cd $basedir/$dir
-          # check all editions
-          for edition in $GO_BUILD_TAGS ;do
-            echo "Running tests in $dir (edition: $edition)"
-            go test -v -tags $edition
-            if [ $? -ne 0 ]; then
-              echo "Tests failed in $dir (edition: $edition)"
-              failed='true'
-            fi
+defaults:
+  run:
+    shell: bash
+
+jobs:
+  go_tests:
+    name: Go tests
+    runs-on: [self-hosted, regular]
+
+    steps:
+      - name: Setup Go environment
+        uses: actions/setup-go@v5
+        with:
+          go-version: "1.24"
+
+      - name: Run Go tests
+        shell: bash
+        run: |
+          basedir=$(pwd)
+          failed='false'
+          for i in $(find / -type f -name '*_test.go');do
+            dir=$(echo $i | sed 's/[a-z_A-Z0-9-]*_test.go$//')
+            cd $basedir/$dir
+            # check all editions
+            for edition in $GO_BUILD_TAGS ;do
+              echo "Running tests in $dir (edition: $edition)"
+              go test -v -tags $edition
+              if [ $? -ne 0 ]; then
+                echo "Tests failed in $dir (edition: $edition)"
+                failed='true'
+              fi
+            done
           done
-        done
-        if [ $failed == 'true' ]; then
-          exit 1
-        fi
+          if [ $failed == 'true' ]; then
+            exit 1
+          fi
